services:
  ha-eufy-sdk-bridge:
    image: ghcr.io/feromonde/ha-eufy-sdk-bridge:latest
    container_name: ha-eufy-sdk-bridge
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      BRIDGE_HOST: "0.0.0.0"
      BRIDGE_PORT: ${BRIDGE_PORT:-3000}
    volumes:
      - ./data:/app/data
