// Write go2rtc.yaml from the live device list, so a camera appears with nobody editing YAML.
//
// go2rtc (bundled in the image) is the ONLY media-protocol code in this project: it pulls the bridge's
// one HTTP Annex-B feed per camera and turns it into RTSP / WebRTC / MSE / HLS. Each camera becomes a
// go2rtc stream sourced from `ffmpeg:<the bridge's /stream URL>#video=copy` — copy, not transcode, so
// go2rtc only remuxes.
//
// The file contains real serials, so it is gitignored and generated at startup.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

/** A device that carries live video — the SDK classes cameras + doorbells as `deviceClass: "camera"`. */
const isCamera = (d) => d.deviceClass === "camera";

export async function writeGo2rtcConfig(cfg, devices) {
  const cams = devices.filter(isCamera);
  const lines = [
    "# generated by ha-eufy-sdk-bridge at startup — do not edit (contains real serials)",
    "api:",
    "  listen: \":1984\"",
    "rtsp:",
    "  listen: \":8554\"",
    "webrtc:",
    "  listen: \":8555\"",
    "streams:",
  ];
  for (const d of cams) {
    // A stream id per camera serial; the source is this bridge's own HTTP feed.
    lines.push(`  ${d.sn}: ffmpeg:http://${cfg.selfHost}:${cfg.port}/stream/${d.sn}#video=copy`);
  }
  const yaml = lines.join("\n") + "\n";
  await mkdir(dirname(cfg.go2rtcConfig), { recursive: true }).catch(() => {});
  await writeFile(cfg.go2rtcConfig, yaml, "utf8");
  return cams.map((d) => d.sn);
}
