// Write go2rtc.yaml from the live device list, so a camera appears with nobody editing YAML.
//
// go2rtc (bundled in the image) is the ONLY media-protocol code in this project: it pulls the bridge's
// one HTTP Annex-B feed per camera and turns it into RTSP / WebRTC / MSE / HLS. go2rtc 1.9.9's native
// HTTP/magic source recognizes Annex-B H.264 (SPS) and H.265/HEVC (VPS) directly, so no ffmpeg process
// is needed in the live path.
//
// The file contains real serials, so it is gitignored and generated at startup.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

// A device that carries live video: a describeDevice() summary with a `stream` path (capabilities
// include camera/video). This matches what HA turns into a camera entity — using deviceClass here
// would miss a camera the SDK downgrades to "other" for sitting behind a HomeBase (not direct P2P).
const isCamera = (d) => Boolean(d.stream);

export async function writeGo2rtcConfig(cfg, devices) {
  const cams = devices.filter(isCamera);
  const lines = [
    "# generated by ha-eufy-sdk-bridge at startup — do not edit (contains real serials)",
    "api:",
    '  listen: ":1984"',
    "rtsp:",
    '  listen: ":8554"',
    "webrtc:",
    '  listen: ":8555"',
    "streams:",
  ];
  for (const d of cams) {
    // Direct HTTP Annex-B source: go2rtc auto-detects H.264 vs H.265 from the bitstream.
    lines.push(`  ${d.sn}: http://${cfg.selfHost}:${cfg.port}/stream/${d.sn}`);
  }
  const yaml = lines.join("\n") + "\n";
  await mkdir(dirname(cfg.go2rtcConfig), { recursive: true }).catch(() => {});
  await writeFile(cfg.go2rtcConfig, yaml, "utf8");
  return cams.map((d) => d.sn);
}
